### ISSUE TITLE
model

### ISSUE THREAD

**Issue by ljh-7** [showlab/VideoLISA#4]
Hello dear author, if I don't have enough hardware to run the training code, will the model in the https://huggingface.co/ZechenBai/VideoLISA-3.8B/tree/main be able to use it directly?

**Comment by JosephPai** [comment]
Sure, this is the pre-trained model. You can directly use it. We will update a demo example to show how to use it in recent days.

**Comment by ljh-7** [comment]
> Sure, this is the pre-trained model. You can directly use it. We will update a demo example to show how to use it in recent days.

I see！Thank you，but I meet the problem :libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory. I try cuda=11.5 11.7and 12.1 but all failed.

**Comment by JosephPai** [comment]
Hi @ljh-7, that seems to be a very typical issue related to your environment. You can try to google it. You'd better ensure torch, cudatoolkit, be compatible with the CUDA version in your server.

**Comment by ljh-7** [comment]
> Hi @ljh-7, that seems to be a very typical issue related to your environment. You can try to google it. You'd better ensure torch, cudatoolkit, be compatible with the CUDA version in your server.

I've fixed this issue, it's caused by a mismatch between the versions of torch, cuda and flash-attn, if you can't find the corresponding version, there is a common way not to use flash-attn
